name: "Setup Conda Standalone"
description: "Use conda-standalone to install conda in CI."
author: "dholth"
branding:
  icon: 'book'
  color: 'green'

# from actions/checkout
inputs:
  repository:
    description: 'Repository name with owner. For example, actions/checkout'
    default: ${{ github.repository }}
  ref:
    description: >
      The branch, tag or SHA to checkout. When checking out the repository that
      triggered a workflow, this defaults to the reference or SHA for that
      event.  Otherwise, uses the default branch.
  token:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.
      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.
      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}
  pattern:
    description: >
      Glob pattern to limit artifact downloads.
    default: conda-*
  group:
    description: >
      Regex matching common part of multiple-artifacts for a single report.
    default: conda-(.*)

runs:
  using: "composite"
  steps:
    - name: Selftest
      shell: bash
      env:
        # necessary to run gh cli
        GH_TOKEN: ${{ github.token }}
        INPUT_REPOSITORY: ${{ inputs.repository }}
        INPUT_ARTIFACT_PATTERN: ${{ inputs.pattern }}
        INPUT_ARTIFACT_GROUP: ${{ inputs.group }}
      run: |
        python $GITHUB_ACTION_PATH/action.py
