name: Selftest

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  selftest:
    runs-on: windows-latest
    steps:
    - uses: actions/cache@v4
      with:
        enableCrossOsArchive: true
        # fyi  'CONDA': 'C:\\Miniconda', is also a thing in GHA. In most cases
        # here, / appears to work fine as a dir separator; when will it fail?

        # runner.temp is on a much faster drive D:\ on Windows runners,
        # otherwise the cache takes too long to restore.
        path: |
          ${{ runner.temp }}/conda-standalone
        key: ${{ runner.os }}
    - uses: actions/checkout@v4
    - uses: dholth/action-conda-standalone/setup-conda-standalone@main
    - name: Conda Install
      env:
        CONDA_PKGS_DIRS: ${{ runner.temp }}\conda-standalone\pkgs
      run: >
        ${{ runner.temp }}\conda-standalone\conda.exe create
        --prefix ${{ runner.temp }}\conda-standalone\env
        --yes
        --file tests/requirements.txt
        --file tests/requirements-${{ runner.os }}.txt
        --file tests/requirements-ci.txt
        --file tests/requirements-s3.txt
        python=${{ matrix.python-version }}
    - name: Conda Info
      run: |
        ${{ runner.temp }}\conda-standalone\conda.exe info
        ${{ runner.temp }}\conda-standalone\env\Scripts\conda.exe info
        dir ${{ env.CONDA_PKGS_DIRS }}