name: Selftest

on: push

jobs:
  selftest:
    runs-on: windows-latest
    steps:
    - uses: actions/cache@v4
      with:
        enableCrossOsArchive: true
        path: |
          ~/conda-standalone
        key: ${{ runner.os }}
    - uses: actions/checkout@v4
    - uses: dholth/action-conda-standalone/setup-conda-standalone@main
    - name: Conda Install
      run: >
        ~/conda-standalone/conda.exe create
        --prefix ~/conda-standalone/env
        --yes
        --file tests/requirements.txt
        --file tests/requirements-${{ runner.os }}.txt
        --file tests/requirements-ci.txt
        --file tests/requirements-s3.txt
        python=${{ matrix.python-version }}
    - name: Conda Info
      run: |
        ~/conda-standalone/conda.exe info
        ~/conda-standalone/env/Scripts/conda.exe info
